import "@/styles/theme.css";
import { Kumbh_Sans as Font } from "next/font/google";
import { Navbar } from "@/components/Nav";

export const runtime = "edge";
export const revalidate = 0;
export const dynamic = "force-dynamic";

export const metadata = {
  title: "SXM Quiz",
  description: "Generated by create next app"
};

const font = Font({ subsets: ["latin"], variable: "--font-sans" });

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={font.variable}>
      <body className="bg-zinc-50">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
