import "@/styles/theme.css";
import { Inter as Font } from "next/font/google";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

const font = Font({ subsets: ["latin"], variable: "--font-sans" });

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={font.variable}>
      <body className="bg-zinc-50">{children}</body>
    </html>
  );
}
